[databases]
nexus_admin_full = host=postgres port=5432 dbname=nexus_data user=nexus_admin_full pool_size=3
nexus_bi_readonly = host=postgres port=5432 dbname=nexus_data user=nexus_bi_ro pool_size=20
nexus_etl_readwrite = host=postgres port=5432 dbname=nexus_data user=nexus_etl_rw pool_size=5
nexus_pe_readonly = host=postgres port=5432 dbname=nexus_data user=nexus_pe_ro pool_size=10
nexus_sales_readonly = host=postgres port=5432 dbname=nexus_data user=nexus_sales_ro pool_size=10

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 6432
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

; Pool settings
pool_mode = transaction
default_pool_size = 20
max_client_conn = 200
min_pool_size = 2

; Logging
log_connections = 1
log_disconnections = 1
log_pooler_errors = 1

; Admin
admin_users = nexus_admin
stats_users = nexus_admin

; Timeouts
server_idle_timeout = 600
client_idle_timeout = 0
